/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;
    uint32_t *pPortAModeReg = (uint32_t*)0x40020000;
    uint32_t *pPortAOutReg =  (uint32_t*)0x40020014;

    *pClkCtrlReg |= 0x01;

    *pPortAModeReg &= ~(3<<4);
    *pPortAModeReg |= (1<<10);

    while(1)
    {
    	*pPortAOutReg |= (1<<5);

    	for(uint32_t i=0 ; i<100000 ; i++);

    	*pPortAOutReg &= ~(1<<5);

    	for(uint32_t i=0 ; i<100000 ; i++);
    }
}
