/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;
    uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
    uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;

    *pClkCtrlReg |= (1 << 3); //

    *pPortDModeReg &= ~(3 << 24); //(CLEAR)
    *pPortDModeReg |= (1 << 24); //(SET)

    while(1){
		*pPortDOutReg |= (1 << 12);

		//delay
		for(uint32_t i=0 ; i<300000 ; i++);

		*pPortDOutReg &= ~(1 << 12);

		for(uint32_t i=0 ; i<300000 ; i++);
    }

}
