/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void delay(void)
{
	for(uint32_t i=0 ; i<300000 ; i++);
}

int main(void)
{
    uint32_t volatile *const pGPIOCMderReg = (uint32_t*)(0x40020800);
    uint32_t volatile *const pInPutDataReg = (uint32_t*)(0x40020800+0x10);
	uint32_t volatile *const pOutPutDataReg = (uint32_t*)(0x40020800+0x14);
	uint32_t volatile *const pClockCtrlReg = (uint32_t*)(0x40023800+0x30);
	uint32_t volatile *const pPullupDownReg = (uint32_t*)(0x40020800+0x0C);

	*pClockCtrlReg |= (1<<2);

	*pGPIOCMderReg &= ~(0xFF);
	*pGPIOCMderReg |= 0x55;

	*pGPIOCMderReg &= ~(0xFF<<16);

	*pPullupDownReg &= ~(0xFF<<16);
	*pPullupDownReg |= (0x55<<16);

	while(1)
	{
		*pOutPutDataReg |= 0x0f;

		*pOutPutDataReg &= ~(1<<0);

		if(!(*pInPutDataReg & (1<<8))){
			delay();
			printf("1\n");
		}
		if(!(*pInPutDataReg & (1<<9))){
			delay();
			printf("2\n");
		}
		if(!(*pInPutDataReg & (1<<10))){
			delay();
			printf("3\n");
		}
		if(!(*pInPutDataReg & (1<<11))){
			delay();
			printf("A\n");
		}

		*pOutPutDataReg |= 0x0f;

		*pOutPutDataReg &= ~(1<<1);

		if(!(*pInPutDataReg & (1<<8))){
			delay();
			printf("4\n");
		}
		if(!(*pInPutDataReg & (1<<9))){
			delay();
			printf("5\n");
		}
		if(!(*pInPutDataReg & (1<<10))){
			delay();
			printf("6\n");
		}
		if(!(*pInPutDataReg & (1<<11))){
			delay();
			printf("B\n");
		}

		*pOutPutDataReg |= 0x0f;

		*pOutPutDataReg &= ~(1<<2);

		if(!(*pInPutDataReg & (1<<8))){
			delay();
			printf("7\n");
		}
		if(!(*pInPutDataReg & (1<<9))){
			delay();
			printf("8\n");
		}
		if(!(*pInPutDataReg & (1<<10))){
			delay();
			printf("9\n");
		}
		if(!(*pInPutDataReg & (1<<11))){
			delay();
			printf("C\n");
		}

		*pOutPutDataReg |= 0x0f;

		*pOutPutDataReg &= ~(1<<3);

		if(!(*pInPutDataReg & (1<<8))){
			delay();
			printf("*\n");
		}
		if(!(*pInPutDataReg & (1<<9))){
			delay();
			printf("0\n");
		}
		if(!(*pInPutDataReg & (1<<10))){
			delay();
			printf("#\n");
		}
		if(!(*pInPutDataReg & (1<<11))){
			delay();
			printf("D\n");
		}
	}


}
